Repository eduNEXT/eox-theming, pull requests merged in 2024-10, with the labels that each got.

#66 refactor: update integration tests workflow and add pytest configuration
  .github/workflows/integration-test.yml
  Makefile
  eox_theming/edxapp_wrapper/tests/__init__.py
  eox_theming/edxapp_wrapper/tests/integration/__init__.py
  eox_theming/edxapp_wrapper/tests/integration/test_backends.py
  eox_theming/management/tests/__init__.py
  eox_theming/management/tests/integration/__init__.py
  eox_theming/management/tests/integration/test_views.py
  eox_theming/management/urls.py
  eox_theming/settings/test.py
  eox_theming/tests/tutor/conftest.py
  eox_theming/tests/tutor/integration.sh
  eox_theming/tests/tutor/integration_test_tutor.py
  eox_theming/tests/tutor/pytest.ini
  requirements/base.txt
  requirements/constraints.txt
  requirements/pip-tools.txt
  requirements/test.in
  requirements/test.txt
  requirements/tox.txt
  scripts/execute_integration_tests.sh
  setup.cfg
  tox.ini
Labels: size/m

#68 chore: drop support for python 3.10 and django 3.2
  .github/workflows/tests.yml
  CHANGELOG.md
  Makefile
  README.rst
  eox_theming/__init__.py
  requirements/constraints.txt
  requirements/django32.txt
  requirements/test.txt
  requirements/tox.txt
  setup.cfg
  setup.py
  tox.ini
Labels: size/s

#69 ci: add dependabot config for enable github action auto update `AP-1514`
  .github/dependabot.yml
  .github/workflows/labeler.yml
  .github/workflows/python-publish.yml
Labels: size/xs
